INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('MADRID','BARCELONA','RELOJ',15,DATE '2013-11-15',1);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('TOLEDO','BARCELONA','RELOJ',35,DATE '2013-11-07',2);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('MALAGA','BARCELONA','RELOJ',45,DATE '2013-11-22',3);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('CADIZ','BARCELONA','RELOJ',135,DATE '2013-11-24',4);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('BARCELONA','CADIZ','RELOJ',12,DATE '2013-11-25',5);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('MADRID','TOLEDO','RELOJ',11,DATE '2013-11-19',6);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('BARCELONA','MALAGA','RELOJ',19,DATE '2013-11-12',2);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('MADRID','MALAGA','RELOJ',215,DATE '2013-11-12',3);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('BARCELONA','CADIZ','RELOJ',87,DATE '2013-11-12',9);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('MADRID','MALAGA','RELOJ',92,DATE '2013-11-13',9);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('MADRID','CADIZ','RELOJ',31,DATE '2013-11-14',1);
INSERT INTO REQUESTS(SOURCE, DESTINATION,SUBJECT,REWARD,DUEDATE,OWNERID) VALUES ('TOLEDO','MALAGA','RELOJ',8,DATE '2013-11-18',2);

